name: Build and deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build application with gradle
        run: ./gradlew buildApp
      - name: Build docker image
        run: docker build -t noirtvt/otakushelter_manga_parser .
      - name: Login to docker registry
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push docker image
        run: docker push noirtvt/otakushelter_manga_parser
      - name: Deploy docker image
        uses: appleboy/ssh-action@master
        with:
          script: |
            docker stop otakushelter_manga_parser
            docker rm otakushelter_manga_parser
            docker image rm noirtvt/otakushelter_manga_parser
            docker run -d --name otakushelter_manga_parser -p 80:8080 -e ENV=${{ secrets.ENV }} -e DRIVER=${{ secrets.DRIVER }} -e USER=${{ secrets.DB_USER }} -e PASSWORD=${{ secrets.DB_PASSWORD }} -e DATABASE=${{ secrets.DATABASE }} noirtvt/otakushelter_manga_parser:latest
          host: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          username: ${{ secrets.USERNAME }}
